### ISSUE TITLE
favicon.ico 404

### ISSUE THREAD

**Issue by xuexb** [52cik/vscode-keyboard-shortcuts#1]
`<link rel="shortcut icon" href="/images/favicon.ico" />` 由于子目录问题, 应该是`./images/`吧?

**Comment by 52cik** [comment]
fixed

**Comment by xuexb** [comment]
@52cik 你既然是fix的, 你的`commit log`里可以带个`fix #1`这样的来提交自动关闭issues额

**Comment by 52cik** [comment]
忘记了。。
